# TODO: add migrate container
# https://firehydrant.com/blog/develop-a-go-app-with-docker-compose/
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - JUST_UNSTABLE=${JUST_UNSTABLE}
        - GO_VERSION=${GO_VERSION}
    ports:
      - "8080:8080"
    tty: true
    links:
      - db
    develop:
      watch:
        - path: go.mod
          action: rebuild
        - path: .
          target: /go/src/github.com/n4vysh/examples/backend
          action: sync
  db:
    image: "postgres:16.1-alpine3.19"
    ports:
      - "5432:5432" # for database client of host OS
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
  migrate: &basemigrate
    profiles: [ "tools" ]
    image: arigaio/atlas
    entrypoint: "atlas migrate apply --url 'postgresql://postgres:password@db/api'"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations
volumes:
  data:
